window.AUDIOBOOK = {
 "book": "레위기에서 만난 예수 그리스도",
 "author": "김동석",
 "chapters": [
  {
   "id": "book-00",
   "no": 0,
   "label": "여는 글",
   "title": "여는 글",
   "subtitle": "",
   "scripture": "",
   "part": "",
   "chars": 734,
   "estSec": 108
  },
  {
   "id": "book-01",
   "no": 1,
   "label": "제 1 장",
   "title": "번제",
   "subtitle": "자기 자신을 온전히 드린 그리스도",
   "scripture": "레위기 1장 1절~17절",
   "part": "제 1 부 하나님께 나아가는 다섯 갈래 길",
   "chars": 9762,
   "estSec": 1436
  },
  {
   "id": "book-02",
   "no": 2,
   "label": "제 2 장",
   "title": "소제",
   "subtitle": "향기로운 삶을 드리는 헌신",
   "scripture": "레위기 2장 1절~16절",
   "part": "",
   "chars": 6051,
   "estSec": 890
  },
  {
   "id": "book-03",
   "no": 3,
   "label": "제 3 장",
   "title": "화목제",
   "subtitle": "하나님과 함께 누리는 식탁",
   "scripture": "레위기 3장 1절~17절",
   "part": "",
   "chars": 6578,
   "estSec": 967
  },
  {
   "id": "book-04",
   "no": 4,
   "label": "제 4 장",
   "title": "속죄제",
   "subtitle": "죄가 드러내는 십자가의 그림자",
   "scripture": "레위기 4장 1절~35절",
   "part": "",
   "chars": 8143,
   "estSec": 1198
  },
  {
   "id": "book-05",
   "no": 5,
   "label": "제 5 장",
   "title": "속건제",
   "subtitle": "빚을 갚으시고 더 채우시는 그리스도",
   "scripture": "레위기 5장 1절~19절",
   "part": "",
   "chars": 6718,
   "estSec": 988
  },
  {
   "id": "book-06",
   "no": 6,
   "label": "제 6 장",
   "title": "제사의 규례",
   "subtitle": "꺼지지 않는 불과 지극한 거룩",
   "scripture": "레위기 6장 1절~30절",
   "part": "",
   "chars": 5470,
   "estSec": 804
  },
  {
   "id": "book-07",
   "no": 7,
   "label": "제 7 장",
   "title": "화목제의 규례",
   "subtitle": "하나님과 함께 앉는 식탁",
   "scripture": "레위기 7장 1절~38절",
   "part": "",
   "chars": 5239,
   "estSec": 770
  },
  {
   "id": "book-08",
   "no": 8,
   "label": "제 8 장",
   "title": "제사장 위임식",
   "subtitle": "물과 기름과 피로 거룩히 구별되다",
   "scripture": "레위기 8장 1절~36절",
   "part": "제 2 부 하나님께 나아가게 하시는 분",
   "chars": 7784,
   "estSec": 1145
  },
  {
   "id": "book-09",
   "no": 9,
   "label": "제 9 장",
   "title": "첫 봉사와 임재하신 영광",
   "subtitle": "명하신 그대로 드린 예배 위에 임한 영광과 불",
   "scripture": "레위기 9장 1절~24절",
   "part": "",
   "chars": 4941,
   "estSec": 727
  },
  {
   "id": "book-10",
   "no": 10,
   "label": "제 10 장",
   "title": "다른 불",
   "subtitle": "나답과 아비후, 그리고 거룩하신 하나님 앞에 드리는 참된 예배",
   "scripture": "레위기 10장 1절~20절",
   "part": "",
   "chars": 7008,
   "estSec": 1031
  },
  {
   "id": "book-11",
   "no": 11,
   "label": "제 11 장",
   "title": "거룩을 위한 구별",
   "subtitle": "정한 짐승과 부정한 짐승, 일상의 식탁에 새긴 거룩",
   "scripture": "레위기 11장 1절~47절",
   "part": "제 3 부 거룩과 부정 사이",
   "chars": 6309,
   "estSec": 928
  },
  {
   "id": "book-12",
   "no": 12,
   "label": "제 12 장",
   "title": "출산과 정결",
   "subtitle": "새 생명이 세상에 들어올 때, 거룩을 향한 정결의 길",
   "scripture": "레위기 12장 1절~8절",
   "part": "",
   "chars": 5052,
   "estSec": 743
  },
  {
   "id": "book-13",
   "no": 13,
   "label": "제 13 장",
   "title": "드러난 부정",
   "subtitle": "악성 피부병 규례에 비친 죄의 모습, 그리고 진영 밖으로",
   "scripture": "레위기 13장 1절~59절",
   "part": "",
   "chars": 4810,
   "estSec": 707
  },
  {
   "id": "book-14",
   "no": 14,
   "label": "제 14 장",
   "title": "회복",
   "subtitle": "악성 피부병에서 정결케 되어, 진영 밖에서 성소로 돌아오는 길",
   "scripture": "레위기 14장 1절~57절",
   "part": "",
   "chars": 4773,
   "estSec": 702
  },
  {
   "id": "book-15",
   "no": 15,
   "label": "제 15 장",
   "title": "유출",
   "subtitle": "가장 은밀한 삶에까지 이르는 부정, 그리고 만지시는 손",
   "scripture": "레위기 15장 1절~33절",
   "part": "",
   "chars": 4884,
   "estSec": 718
  },
  {
   "id": "book-16",
   "no": 16,
   "label": "제 16 장",
   "title": "속죄일",
   "subtitle": "일 년에 한 번 휘장 너머로, 두 염소가 가리킨 단번의 속죄",
   "scripture": "레위기 16장 1절~34절",
   "part": "제 4 부 휘장 안으로, 단번에",
   "chars": 5538,
   "estSec": 814
  },
  {
   "id": "book-17",
   "no": 17,
   "label": "제 17 장",
   "title": "생명의 피",
   "subtitle": "오직 한 제단으로, 생명이 피에 있으므로 피가 속죄하느니라",
   "scripture": "레위기 17장 1절~16절",
   "part": "",
   "chars": 4699,
   "estSec": 691
  },
  {
   "id": "book-18",
   "no": 18,
   "label": "제 18 장",
   "title": "거룩한 경계",
   "subtitle": "성과 가정을 지키시는 하나님의 울타리, 애굽도 가나안도 아닌 삶",
   "scripture": "레위기 18장 1절~30절",
   "part": "제 5 부 거룩하신 분과 동행하는 삶",
   "chars": 5162,
   "estSec": 759
  },
  {
   "id": "book-19",
   "no": 19,
   "label": "제 19 장",
   "title": "거룩한 일상",
   "subtitle": "내가 거룩하니 너희도 거룩하라, 네 이웃을 네 자신같이 사랑하라",
   "scripture": "레위기 19장 1절~37절",
   "part": "",
   "chars": 4733,
   "estSec": 696
  },
  {
   "id": "book-20",
   "no": 20,
   "label": "제 20 장",
   "title": "거룩의 값",
   "subtitle": "거룩을 어긴 죄의 무게, 그리고 너희를 거룩하게 하시는 여호와",
   "scripture": "레위기 20장 1절~27절",
   "part": "",
   "chars": 4839,
   "estSec": 712
  },
  {
   "id": "book-21",
   "no": 21,
   "label": "제 21 장",
   "title": "거룩한 제사장",
   "subtitle": "더 높은 거룩으로 부름받은 자, 흠 없으신 대제사장을 가리켜",
   "scripture": "레위기 21장 1절~24절",
   "part": "",
   "chars": 4699,
   "estSec": 691
  },
  {
   "id": "book-22",
   "no": 22,
   "label": "제 22 장",
   "title": "흠 없는 제물",
   "subtitle": "거룩한 것을 거룩히, 하나님께 드리는 온전한 제물",
   "scripture": "레위기 22장 1절~33절",
   "part": "",
   "chars": 4712,
   "estSec": 693
  },
  {
   "id": "book-23",
   "no": 23,
   "label": "제 23 장",
   "title": "여호와의 절기",
   "subtitle": "그리스도의 죽음과 부활과 성령과 재림을 담은 거룩한 달력",
   "scripture": "레위기 23장 1절~44절",
   "part": "",
   "chars": 4514,
   "estSec": 664
  },
  {
   "id": "book-24",
   "no": 24,
   "label": "제 24 장",
   "title": "꺼지지 않는 등불",
   "subtitle": "늘 켜진 등불과 진설병, 그리고 거룩히 여겨야 할 그분의 이름",
   "scripture": "레위기 24장 1절~23절",
   "part": "",
   "chars": 4581,
   "estSec": 674
  },
  {
   "id": "book-25",
   "no": 25,
   "label": "제 25 장",
   "title": "희년",
   "subtitle": "빚이 탕감되고 종이 풀려나며 기업이 회복되는 자유의 해",
   "scripture": "레위기 25장 1절~55절",
   "part": "",
   "chars": 4713,
   "estSec": 693
  },
  {
   "id": "book-26",
   "no": 26,
   "label": "제 26 장",
   "title": "복과 저주",
   "subtitle": "두 길 앞에 선 백성, 그러나 끝내 언약을 기억하시는 하나님",
   "scripture": "레위기 26장 1절~46절",
   "part": "",
   "chars": 4581,
   "estSec": 674
  },
  {
   "id": "book-27",
   "no": 27,
   "label": "제 27 장",
   "title": "서원",
   "subtitle": "자신과 소유를 여호와께 온전히 드리는 헌신, 레위기를 닫는 부름",
   "scripture": "레위기 27장 1절~34절",
   "part": "제 6 부 값을 치른 헌신",
   "chars": 5452,
   "estSec": 802
  },
  {
   "id": "book-28",
   "no": 28,
   "label": "닫는 글",
   "title": "닫는 글",
   "subtitle": "",
   "scripture": "",
   "part": "",
   "chars": 444,
   "estSec": 65
  }
 ]
};
